---------------------------------------------------------------------------
-- This script incorporates the REF_CHANGE_AGENT table for session auditing and adds the change_agent_id column to the R_BASE_ARCHIVE table. 
-- It logs session and client metadata for auditing changes, allowing traceability of who made modifications to R_BASE table.
-- IMPORTANT!!! This script should be executed as main schema user that owns the tables.
-- created on 07/2025 by IsmailO
--------------------------------------------------------------------------

-- Create the ref_change_agent table
CREATE TABLE ref_change_agent (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Unique identifier for each change agent
    session_user VARCHAR2(255),                            -- Session user
    client_identifier VARCHAR2(255) DEFAULT 'UNKNOWN_CLIENT_IDENTIFIER',  -- Default value if null
    os_user VARCHAR2(255),                                  -- Operating system user
    host VARCHAR2(255),                                     -- Host machine
    client_program_name VARCHAR2(255),                      -- Client program name
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP         -- Timestamp when the record was created
);

--Add comment
COMMENT ON TABLE REF_CHANGE_AGENT  IS 'Logs session and client metadata for auditing changes, allowing traceability of who made modifications to R_BASE.';

--Roles,privs and public synonyms
--For UC only. Other databases will expect to fail.  
GRANT READ ON REF_CHANGE_AGENT TO HDB_READ_ROLE;
GRANT SELECT ON REF_CHANGE_AGENT TO HDB_WRITE_ROLE;

GRANT SELECT, UPDATE, DELETE, INSERT ON REF_CHANGE_AGENT TO APP_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON REF_CHANGE_AGENT TO REF_META_ROLE;
GRANT SELECT, UPDATE, DELETE, INSERT ON REF_CHANGE_AGENT TO SAVOIR_FAIRE;
GRANT SELECT, UPDATE, DELETE, INSERT ON REF_CHANGE_AGENT TO CALC_DEFINITION_ROLE;
CREATE PUBLIC SYNONYM REF_CHANGE_AGENT FOR REF_CHANGE_AGENT;


-- Create an index for efficient lookups
CREATE UNIQUE INDEX idx_ref_change_agent_lookup ON ref_change_agent (
    session_user, client_identifier, os_user, host, client_program_name
);


--Add new columns for R_BASE_ARCHIVE table and FK
ALTER TABLE r_base_archive ADD change_agent_id NUMBER;
ALTER TABLE r_base_archive ADD CONSTRAINT fk_ref_change_agent FOREIGN KEY (change_agent_id) REFERENCES ref_change_agent(id);


-- Trigger: r_base_after_delete
CREATE OR REPLACE TRIGGER r_base_after_delete
AFTER DELETE ON r_base
FOR EACH ROW
DECLARE
    v_change_agent_id NUMBER;
BEGIN
    -- Lookup or insert into change_agent table
    BEGIN
        SELECT id INTO v_change_agent_id
        FROM ref_change_agent
        WHERE session_user = COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER'))
          AND client_identifier = COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'UNKNOWN_CLIENT_IDENTIFIER') 
          AND os_user = SYS_CONTEXT('USERENV', 'OS_USER')
          AND host = SYS_CONTEXT('USERENV', 'HOST')
          AND client_program_name = SYS_CONTEXT('USERENV', 'MODULE')
        FETCH FIRST ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO ref_change_agent (
                session_user,
                client_identifier,
                os_user,
                host,
                client_program_name
                
            )
            VALUES (
                COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER')),
                COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'UNKNOWN_CLIENT_IDENTIFIER'),
                SYS_CONTEXT('USERENV', 'OS_USER'),
                SYS_CONTEXT('USERENV', 'HOST'),
                SYS_CONTEXT('USERENV', 'MODULE')
            )
            RETURNING id INTO v_change_agent_id;
    END;

    -- Insert into r_base_archive with change_agent_id
    INSERT INTO r_base_archive (
        site_datatype_id,
        interval,
        start_date_time,
        end_date_time,
        value,
        agen_id,
        overwrite_flag,
        date_time_loaded,
        validation,
        collection_system_id,
        loading_application_id,
        method_id,
        computation_id,
        archive_reason,
        date_time_archived,
        data_flags,
        change_agent_id
    )
    VALUES (
        :old.site_datatype_id,
        :old.interval,
        :old.start_date_time,
        :old.end_date_time,
        :old.value,
        :old.agen_id,
        :old.overwrite_flag,
        :old.date_time_loaded,
        :old.validation,
        :old.collection_system_id,
        :old.loading_application_id,
        :old.method_id,
        :old.computation_id,
        'DELETE',
        SYSDATE,
        :old.data_flags,
        v_change_agent_id
    );


/*  now delete from the interval table if it exists  the thought was just try the delete
    if it works then OK otherwise a query to do the count and then do the delete seems
    to do twice the amount of work

*/
--  modified the delete August 2007 by M.  Bogner to delete regardless of date_time_loaded
--  decided to keep it simple and don't over complicate it ,  for now...
--  modified the delete December 2007 by M.  Bogner to delete with respect to date_time_loaded
--  we just can't make up our minds...
        hdb_utilities.delete_from_interval(
         :old.site_datatype_id,
         :old.interval,
         :old.start_date_time,
         :old.end_date_time,
         :old.date_time_loaded);

end;
/

-- Trigger: r_base_after_update
CREATE OR REPLACE TRIGGER r_base_after_update
AFTER UPDATE ON r_base
FOR EACH ROW
DECLARE
    v_change_agent_id NUMBER;
BEGIN
    -- Lookup or insert into change_agent table
    BEGIN
        SELECT id INTO v_change_agent_id
        FROM ref_change_agent
        WHERE session_user = COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER'))
          AND client_identifier = COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'UNKNOWN_CLIENT_IDENTIFIER') 
          AND os_user = SYS_CONTEXT('USERENV', 'OS_USER')
          AND host = SYS_CONTEXT('USERENV', 'HOST')
          AND client_program_name = SYS_CONTEXT('USERENV', 'MODULE')
        FETCH FIRST ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO ref_change_agent (
                session_user,
                client_identifier,
                os_user,
                host,
                client_program_name
            )
            VALUES (
                COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER')),
                COALESCE(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), 'UNKNOWN_CLIENT_IDENTIFIER'),
                SYS_CONTEXT('USERENV', 'OS_USER'),
                SYS_CONTEXT('USERENV', 'HOST'),
                SYS_CONTEXT('USERENV', 'MODULE')
            )
            RETURNING id INTO v_change_agent_id;
    END;

    -- Archive the row that was changed
    INSERT INTO r_base_archive (
        site_datatype_id,
        interval,
        start_date_time,
        end_date_time,
        value,
        agen_id,
        overwrite_flag,
        date_time_loaded,
        validation,
        collection_system_id,
        loading_application_id,
        method_id,
        computation_id,
        archive_reason,
        date_time_archived,
        data_flags,
        change_agent_id
    )
    VALUES (
        :old.site_datatype_id,
        :old.interval,
        :old.start_date_time,
        :old.end_date_time,
        :old.value,
        :old.agen_id,
        :old.overwrite_flag,
        :old.date_time_loaded,
        :old.validation,
        :old.collection_system_id,
        :old.loading_application_id,
        :old.method_id,
        :old.computation_id,
        'UPDATE',
        SYSDATE,
        :old.data_flags,
        v_change_agent_id
    );
     
-- removed overwrite flag logic August 2007 by M. Bogner due to HDB committee decision
-- removed validation logic March 2008 by M. Bogner due to HDB committee decision
-- As of March 2008 only keep data from being merged if it has an F (failed) validation

--  if nvl(:new.validation,'F') not in ('F','Z') or :new.overwrite_flag='O' then
--  if nvl(:new.validation,'F') not in ('F','Z') then
--    select count(*) into v_count from ref_interval_copy_limits
--      where :new.site_datatype_id=site_datatype_id
--        and :new.interval=interval;
--    only if there's a derivation spec or it's a forced 'O'verwrite
--      if v_count!=0 or :new.overwrite_flag='O' then
      if nvl(:new.validation,'x') not in ('F') then
          hdb_utilities.merge_into_r_interval(
            :new.site_datatype_id,
            :new.interval,
            :new.start_date_time,
            :new.end_date_time,
            :new.value,
            :new.validation,
            :new.overwrite_flag,
            :new.method_id,
            :new.data_flags,
            :new.date_time_loaded
           );
      end if;
end;
/


--update version table
INSERT INTO TSDB_PROPERTY (PROP_NAME, PROP_VALUE) VALUES ('4.15.7', 'REF_CHANGE_AGENT table for session audits and change_agent(id) column added to r_base_archive.');


--Commit changes
commit;