-- V1_0_1__Create_Users_and_Roles.sql
-- Baseline schema setup: Roles and Users

-- Roles
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE CZAR_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE HDB_META_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE REF_META_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE APP_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE DECODES_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE CALC_DEFINITION_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE SAVOIR_FAIRE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE MODEL_PRIV_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE MONTHLY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Users
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ${hdb_user} IDENTIFIED BY "${hdb_password}" DEFAULT TABLESPACE HDB_data TEMPORARY TABLESPACE HDB_temp QUOTA UNLIMITED ON HDB_data QUOTA UNLIMITED ON HDB_idx';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
GRANT CONNECT, RESOURCE, HDB_META_ROLE, REF_META_ROLE to ${hdb_user};
-- Grant access to dictionary views needed by triggers
GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO ${hdb_user};
GRANT SELECT ON SYS.DBA_ROLES TO ${hdb_user};

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER decodes IDENTIFIED BY "${hdb_password}" DEFAULT TABLESPACE HDB_data TEMPORARY TABLESPACE HDB_temp QUOTA UNLIMITED ON HDB_data QUOTA UNLIMITED ON HDB_idx';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
GRANT CONNECT, RESOURCE, DECODES_ROLE to decodes;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER CP_PROCESS IDENTIFIED BY "${hdb_password}" DEFAULT TABLESPACE HDB_data TEMPORARY TABLESPACE HDB_temp QUOTA UNLIMITED ON HDB_data QUOTA UNLIMITED ON HDB_idx';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
GRANT CONNECT, RESOURCE to CP_PROCESS;

-- Permissions for CP_PROCESS
GRANT app_role TO CP_PROCESS;
GRANT decodes_role TO CP_PROCESS;
GRANT calc_definition_role TO CP_PROCESS;
ALTER USER CP_PROCESS DEFAULT ROLE ALL;

-- SYSDBA grants to HDBDBA for migration tasks (if needed, but usually SYS performs migration)
-- GRANT DBA TO ${hdb_user};
GRANT SELECT ON DBA_ROLES TO ${hdb_user};
GRANT UNLIMITED TABLESPACE TO ${hdb_user};

-- Additional HDB Users (from PERMISSIONS/BASE_SCRIPTS/permissions.sh)
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER psswd_user IDENTIFIED BY "${hdb_password}" DEFAULT TABLESPACE HDB_data TEMPORARY TABLESPACE HDB_temp QUOTA 10M ON HDB_data';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
GRANT CONNECT, CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER TO psswd_user;
GRANT SELECT ON SYS.dba_role_privs TO psswd_user;
GRANT SELECT ON SYS.user$ TO psswd_user;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER app_user IDENTIFIED BY "${hdb_password}" DEFAULT TABLESPACE HDB_user TEMPORARY TABLESPACE HDB_temp QUOTA UNLIMITED ON HDB_user';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
GRANT CREATE SESSION TO app_user;
GRANT app_role TO app_user;
GRANT ref_meta_role TO app_user;
GRANT hdb_meta_role TO app_user;
GRANT model_priv_role TO app_user;
ALTER USER app_user DEFAULT ROLE NONE;
