flyway.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
flyway.jdbcProperties.internal_logon=sysdba
flyway.user=sys
flyway.password=***
flyway.schemas=HDBDBA,DECODES,PSSWD_USER,APP_USER
flyway.placeholders.hdb_user=HDBDBA
flyway.placeholders.hdb_password=HDBDBA
flyway.oracle.sqlplus=false
flyway.baselineOnMigrate=true
flyway.locations=filesystem:flyway_migration/sql/base
flyway.table=flyway_schema_history
flyway.sqlMigrationPrefix=V
flyway.outOfOrder=true
